<?php

/**
 * @file
 * Provides a wrapper for the CoreLogic Connect2Data API.
 */

/**
 * Implements hook_permission().
 */
function connect2data_api_permission() {
  return array(
    'administer connect2data_api' =>  array(
      'title' => t('Administer Connect2Data API'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function connect2data_api_menu() {
  $items['admin/config/services/connect2data_api'] = array(
    'title' => 'Connect2Data API',
    'description' => 'Configure Connect2Data API settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('connect2data_api_admin_settings_form'),
    'access arguments' => array('administer connect2data_api'),
    'file' => 'connect2data_api.admin.inc',
  );

  return $items;
}

/**
 * Makes a request to CoreLogic Connect2Data API.
 */
function connect2data_api_get_detailed_subject_report($property_criteria) {
  try {
    $api = connect2data_api_get_object();
    return $api->getDetailedSubjectReport($property_criteria);
  }
  catch (Connect2DataAPIException $e) {
    watchdog_exception('connect2data_api_get_detailed_subject_report', $e);
  }
}

/**
 * Returns an instance of the Connect2DataAPI class.
 *
 * @see connect2data_api_get_detailed_subject_report()
 */
function connect2data_api_get_object() {
  $login_account_id = variable_get('connect2data_api_login_account_id');
  $login_account_pw = variable_get('connect2data_api_login_account_pw');
  return new Connect2DataAPI($login_account_id, $login_account_pw);
}