<?php

/**
 * @file
 * Provides a wrapper for the CoreLogic Connect2Data API.
 */

define('CONNECT2DATA_API_CACHE_LIFETIME_DETAILED_SUBJECT_REPORT', 180);
define('CONNECT2DATA_API_RESPONSE_SOURCE_CACHE', 0);
define('CONNECT2DATA_API_RESPONSE_SOURCE_HTTP', 1);

/**
 * Implements hook_permission().
 */
function connect2data_api_permission() {
  return array(
    'administer connect2data_api' => array(
      'title' => t('Administer Connect2Data API'),
    ),
    'make request to connect2data_api' => array(
      'title' => t('Make a request to the Connect2Data API'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function connect2data_api_menu() {
  $items['admin/config/services/connect2data_api'] = array(
    'title' => 'Connect2Data API',
    'description' => 'Configure Connect2Data API settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('connect2data_api_admin_settings_form'),
    'access arguments' => array('administer connect2data_api'),
    'file' => 'connect2data_api.admin.inc',
  );

  $items['connect2data_api/history'] = array(
    'title' => 'History of requests to the Connect2Data',
    'description' => 'Displays a history of requests that were made to the Connect2Data API.',
    'page callback' => 'connect2data_api_history_page',
    'access arguments' => array('administer connect2data_api'),
    'file' => 'connect2data_api.admin.inc',
  );

  return $items;
}

/**
 * Makes a request to CoreLogic Connect2Data API.
 */
function connect2data_api_get_detailed_subject_report($property_criteria, $request_reason) {
  try {
    $api = new Connect2DataAPI();
    return $api->getDetailedSubjectReport($property_criteria, $request_reason);
  }
  catch (Connect2DataAPIException $e) {
    watchdog_exception('connect2data_api', $e);
  }
}
