<?php

/**
 * @file
 * Implements miscellaneous hooks.
 */

/**
 * Implements hook_admin_menu_output_alter().
 *
 * Prevents 'User counts' block from displaying to a user
 * which has not an administrator user role.
 */
function reiscout_misc_admin_menu_output_alter(&$content) {
  if (isset($content['users'])) {
    $role_admin = user_role_load_by_name('administrator');
    if (!user_has_role($role_admin->rid)) {
      unset($content['users']);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function reiscout_misc_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  $form['#validate'][] = 'reiscout_misc_user_profile_form_validate';
}

/**
 * Form validation handler for 'user_profile_form' form.
 *
 * Validates 'Phone Number' and 'Website' fields.
 */
function reiscout_misc_user_profile_form_validate(&$form, &$form_state, $form_id) {
  $field_user_phone_number = $form_state['values']['field_user_phone_number'][LANGUAGE_NONE][0]['value'];
  $field_user_website = $form_state['values']['field_user_website'][LANGUAGE_NONE][0]['value'];

  if ($field_user_phone_number) {
    if (!preg_match('!\d{2,}!', $field_user_phone_number)) {
      $t_args = array('%phone' => $field_user_phone_number);
      form_set_error('field_user_phone_number', t('The phone number %phone is not valid.', $t_args));
    }
  }

  if ($field_user_website) {
    if (!preg_match('!.+?\..{2,}!', $field_user_website)) {
      $t_args = array('%url' => $field_user_website);
      form_set_error('field_user_website', t('The website URL %url is not valid.', $t_args));
    }
  }
}

/**
 * Checks if the current user has 'administrator' role.
 */
function _reiscout_misc_user_has_administrator_role() {
  $role_admin = user_role_load_by_name('administrator');
  return user_has_role($role_admin->rid);
}
