<?php

/**
 * @file
 * Provides a form for requesting data from the CoreLogic Connect2Data.
 */

/**
 * Implements hook_permission().
 */
function connect2data_form_permission() {
  return array(
    'use connect2data_form' =>  array(
      'title' => t('Use Connect2Data Form'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function connect2data_form_menu() {
  $items['connect2data'] = array(
    'title' => 'Connect2Data Form',
    'description' => 'A form for requesting data from the CoreLogic Connect2Data.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('connect2data_form'),
    'access arguments' => array('use connect2data_form'),
    'file' => 'connect2data_form.pages.inc',
  );

  return $items;
}
