<?php

/**
 * @file
 * Implements miscellaneous hooks.
 */

/**
 * Implements hook_admin_menu_output_alter().
 *
 * Prevents 'User counts' block from displaying to a user
 * which has not an administrator user role.
 */
function reiscout_misc_admin_menu_output_alter(&$content) {
  if (isset($content['users'])) {
    $role_admin = user_role_load_by_name('administrator');
    if (!user_has_role($role_admin->rid)) {
      unset($content['users']);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function reiscout_misc_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  $form['#attached']['css'][] = array(
    'data' => '#edit-field-user-postal-address .form-item-field-user-postal-address-und-0-country {display: none}',
    'type' => 'inline',
  );

  $form['#validate'][] = 'reiscout_misc_user_profile_form_validate';
}

/**
 * Form validation handler for 'user_profile_form' form.
 *
 * Validates 'Phone Number' and 'Website' fields.
 */
function reiscout_misc_user_profile_form_validate(&$form, &$form_state) {
  $field_user_phone_number = $form_state['values']['field_user_phone_number'][LANGUAGE_NONE][0]['value'];
  $field_user_website = $form_state['values']['field_user_website'][LANGUAGE_NONE][0]['value'];

  if ($field_user_phone_number) {
    if (!preg_match('!\d{2,}!', $field_user_phone_number)) {
      $t_args = array('%phone' => $field_user_phone_number);
      form_set_error('field_user_phone_number', t('The phone number %phone is not valid.', $t_args));
    }
  }

  if ($field_user_website) {
    if (!preg_match('!.+?\..{2,}!', $field_user_website)) {
      $t_args = array('%url' => $field_user_website);
      form_set_error('field_user_website', t('The website URL %url is not valid.', $t_args));
    }
  }
}

/**
 * Implements hook_user_presave().
 */
function reiscout_misc_user_presave(&$edit, $account, $category) {
  if ($edit['field_user_postal_address'][LANGUAGE_NONE][0]['thoroughfare']) {
    $edit['field_user_postal_address'][LANGUAGE_NONE][0]['thoroughfare'] = _reiscout_misc_standardize_address_thoroughfare($edit['field_user_postal_address'][LANGUAGE_NONE][0]['thoroughfare']);
  }
}

/**
 * Standardizes an address thoroughfare.
 *
 * Some incorrectly filled addresses cannot be fully processed, e.g.:
 *   [465Brown] lee Rd SW
 *   10270 E Taron [Dr 403]
 *   270 17th [# 1608 NW]
 *
 * @todo: Find and use some service, e.g., USPS to validate and standardize
 *        addresses.
 */
function _reiscout_misc_standardize_address_thoroughfare($thoroughfare) {
  $from = array(
    '!(\.|,)!',
    '! (Street|Str)$!i',
    '! (Street|Str) !i',
    '! Road$!i',
    '! Road !i',
    '! Avenue$!i',
    '! Avenue !i',
    '! (Boulevard|Blv)$!i',
    '! (Boulevard|Blv) !i',
    '! Lane$!i',
    '! Lane !i',
    '! Drive$!i',
    '! Drive !i',
    '! Highway$!i',
    '! Highway !i',
    '! (Parkway|Pky)$!i',
    '! (Parkway|Pky) !i',
    '! Place$!i',
    '! Place !i',
    '! Circle$!i',
    '! Circle !i',
    '! Connector$!i',
    '! Connector !i',
    '! Court$!i',
    '! Court !i',
    '! Rdg$!i',
    '! Rdg !i',
    '! Terrace$!i',
    '! Terrace !i',
    '! Trace$!i',
    '! Trace !i',
    '! (Tr|Trl)$!i',
    '! (Tr|Trl) !i',
    '! Xing$!i',
    '! Xing !i',
    '! North !i',
    '! South !i',
    '! East !i',
    '! West !i',
    '! Northeast !i',
    '! Northwest !i',
    '! Southeast !i',
    '! Southwest !i',
    '! North$!i',
    '! South$!i',
    '! East$!i',
    '! West$!i',
    '! Northeast$!i',
    '! Northwest$!i',
    '! Southeast$!i',
    '! Southwest$!i',
    '!\s{2,}!',
    '! N E$!i',
    '! N E !i',
    '! N W$!i',
    '! N W !i',
    '! S E$!i',
    '! S E !i',
    '! S W$!i',
    '! S W !i',
    '! Apartment !i',
    '! Building !i',
    '! Floor !i',
    '! Room !i',
    '! Suite !i',
    '! (?:Apt|Ste|Unit)(?:\s+#?|#)\s*([0-9a-z\-/]+)!i',
    '! (?:Apt|Ste|Unit)([0-9]+)!i',
    '! Rm\s*#?\s*([0-9a-z\-/]+)!i',
    '! #([0-9a-z\-/]+)!i',
    '!P\s*O\s+Box\s*(\d+)!i',
  );

  $to = array(
    ' ',
    ' St',
    ' St ',
    ' Rd',
    ' Rd ',
    ' Ave',
    ' Ave ',
    ' Blvd',
    ' Blvd ',
    ' Ln',
    ' Ln ',
    ' Dr',
    ' Dr ',
    ' Hwy',
    ' Hwy ',
    ' Pkwy',
    ' Pkwy ',
    ' Pl',
    ' Pl ',
    ' Cir',
    ' Cir ',
    ' Conn',
    ' Conn ',
    ' Ct',
    ' Ct ',
    ' Ridge',
    ' Ridge ',
    ' Ter',
    ' Ter ',
    ' Trce',
    ' Trce ',
    ' Trail',
    ' Trail ',
    ' Crossing',
    ' Crossing ',
    ' N ',
    ' S ',
    ' E ',
    ' W ',
    ' NE ',
    ' NW ',
    ' SE ',
    ' SW ',
    ' N',
    ' S',
    ' E',
    ' W',
    ' NE',
    ' NW',
    ' SE',
    ' SW',
    ' ',
    ' NE',
    ' NE ',
    ' NW',
    ' NW ',
    ' SE',
    ' SE ',
    ' SW',
    ' SW ',
    ' Apt ',
    ' Bldg ',
    ' Fl ',
    ' Rm ',
    ' Ste ',
    ' # $1',
    ' # $1',
    ' Rm $1',
    ' # $1',
    'PO Box $1',
  );

  return trim(preg_replace($from, $to, $thoroughfare));
}

/**
 * Checks if the current user has 'administrator' role.
 */
function _reiscout_misc_user_has_administrator_role() {
  $role_admin = user_role_load_by_name('administrator');
  return user_has_role($role_admin->rid);
}
