<?php

/**
 * @file
 * Customize commerce modules behaviours for reiscout project needs.
 *
 * Implements address access control.
 */

define('COMMERCE_REISCOUT_PROPERTY_NODE_TYPE', 'property');
define('COMMERCE_REISCOUT_PROPERTY_ADDRESS_ACCESS_PRODUCT_SKU', 'property-address-access');

/**
 * Return display nodes associated with purchased products by user.
 *
 * @param integer $uid user id
 * @param string $order_status an order status, default to 'completed'
 * @param string $sku product sku
 */
function commerce_reiscout_get_purchased_display_entities($uid, $sku = '', $order_status = 'completed') {

  $purchased_entities = &drupal_static(__FUNCTION__ . '_' .$uid . '_' . $sku);
  if (!empty($purchased_entities)) {
    return $purchased_entities;
  }

  $purchased_entities = array();
  $orders = commerce_order_load_multiple(array(), array('uid' => $uid, 'status' => $order_status)); //

  foreach ($orders as $order) {
    $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
    foreach ($order_wrapper->commerce_line_items->getIterator() as $line_item_wrapper) {
      if (empty($sku) || $sku == $line_item_wrapper->commerce_product->sku->value()) {
        $line_item = $line_item_wrapper->value();
        $purchased_entities[] = $line_item->data['context']['entity'];
      }
    }
  }

  return $purchased_entities;
}

/**
 * A helper wrapper for commerce_reiscout_get_purchased_display_entities()
 */
function commerce_reiscout_get_user_purchased_picture_nids() {
  $entities = commerce_reiscout_get_purchased_display_entities($GLOBALS['user']->uid, COMMERCE_REISCOUT_PROPERTY_ADDRESS_ACCESS_PRODUCT_SKU, 'completed');
  $nids = array();
  foreach ($entities as $entity) {
    if ($entity['entity_type'] == 'node') {
      $nids[] = $entity['entity_id'];
    }
  }
  return $nids;
}

/**
 * Implements hook_field_access.
 */
function commerce_reiscout_field_access($op, $field, $entity_type, $entity, $account) {

  // Do nothing if current user is admin
  if ($account->uid == 1) {
    return;
  }

  // Access control for field_address in picture node.
  if ($op == 'view' && $entity_type == 'node' && !empty($entity->type) && $entity->type == COMMERCE_REISCOUT_PROPERTY_NODE_TYPE
  && $field['field_name'] == 'field_address_text') {

    // Allow access if user is an author.
    if ($entity->uid == $account->uid) {
      return TRUE;
    }

    // Allow access if user purchased the node.
    if (in_array($entity->nid, commerce_reiscout_get_user_purchased_picture_nids())) {
      return TRUE;
    }

    // Deny access otherwise
    return FALSE;
  }
}
