<?php

/**
 * @file
 * Reiscout Connect2data API -
 * 1. Getting property owner info via CoreLogic.
 * 2. Write received data to address field of property node.
 */

// ToDo: rename module to connect2data_api

// ToDo: move all project specific code from this module

// Define constants
// ToDo: rename cont to modulename_API_URL
const API_URL = 'https://staging.connect2data.com/';


/**
 * Construct request to connect2data.com (CoreLogic)
 * and parse response.
 *
 * ToDo: this function should be moved to reiscout_owner_info module
 * a it doing address specific things.
 *
 * reiscout_connect2data module should contain ONLY API code agnostic to project.
 */
function reiscout_connect2data_api_get_data($nid) {

  $response = reiscout_connect2data_api_send_request($nid);
  if ($response === FALSE) {
    return FALSE;
  }

  $xml = simplexml_load_string($response, 'simple_xml_extended');

  // Check for valid XML
  if ($xml === FALSE) {
    watchdog('reiscout_connect2data_api', 'XML parsing error: not a valid XML.', array(), WATCHDOG_ERROR);
    drupal_set_message("XML parsing error: not a valid XML.", "error");
    return FALSE;
  }

  // Parse returned XML and format output
  $output = 'RESPONSE FROM CONNECT2DATA.COM:';
  $output .= '<br />-------<br />';
  $output .= $xml->RESPONSE->Attribute('ResponseDateTime');
  $output .= '<br />';
  $output .= 'Status: ' . $xml->RESPONSE->RESPONSE_DATA->PROPERTY_INFORMATION_RESPONSE->STATUS->Attribute('_Condition');
  $output .= ' | Code: ' . $xml->RESPONSE->RESPONSE_DATA->PROPERTY_INFORMATION_RESPONSE->STATUS->Attribute('_Code');
  $output .= '<br />';
  $output .= $xml->RESPONSE->RESPONSE_DATA->PROPERTY_INFORMATION_RESPONSE->STATUS->Attribute('_Description');
  $output .= '<br />-------';

  // Display output to administrator
  // ToDo: create user_is_admin() and place in reicout_misc.
  $role = user_role_load_by_name('administrator');
  if (user_has_role($role->rid)) {
    drupal_set_message($output);
  }

  $result = reiscout_connect2data_api_save_address($nid);

  return $result;
}


/**
 * Write data to address field
 * ToDo: Move it to reiscout_owner_info module.
 */
function reiscout_connect2data_api_save_address($nid, $data = NULL) {

  // Emulate received data and then write to address field
  $debug_addresses = fillup_debug_adresses();
  $default_address = array(
    'first_name'  => 'Garry',
    'last_name'   => 'Moor',
    'address'     => '5270 Forest Downs Lane',
    'city'        => 'College Park',
    'state'       => 'GA',
    'zip'         => 30152,
    'country'     => 'US',
  );

  $address = array();

  if (array_key_exists($nid, $debug_addresses)) {
    $address = $debug_addresses[$nid];
  }
  else {
    $address = $default_address;
  }

  $node = node_load($nid);
  if ($node == NULL) {
    drupal_set_message('Cannot load node: ' . $nid, "error");
    return FALSE;
  }

  // Set the new address field values
  // ToDo: improve code reading, create $address var and put it to node once.
  $node->field_owner_postal_address[LANGUAGE_NONE][0]['first_name'] = $address['first_name'];
  $node->field_owner_postal_address[LANGUAGE_NONE][0]['last_name'] = $address['last_name'];
  $node->field_owner_postal_address[LANGUAGE_NONE][0]['name_line'] = $address['first_name'] . ' ' . $address['last_name'];
  $node->field_owner_postal_address[LANGUAGE_NONE][0]['thoroughfare'] = $address['address'];
  $node->field_owner_postal_address[LANGUAGE_NONE][0]['locality'] = $address['city'];
  $node->field_owner_postal_address[LANGUAGE_NONE][0]['administrative_area'] = $address['state'];
  $node->field_owner_postal_address[LANGUAGE_NONE][0]['postal_code'] = $address['zip'];
  $node->field_owner_postal_address[LANGUAGE_NONE][0]['country'] = $address['country'];

  // Optional lines to make this change a new revision
  $node->revision = 1;
  $node->log = 'Owner Postal Address was programmatically updated on ' . date('c');

  // Save the updated node
  try {
    node_save($node);
    drupal_set_message('Owner Postal Address was updated on ' . date('c'));
    return TRUE;
  }
  catch (Exception $e) {
    watchdog('reiscout_connect2data_api', 'Node save error: ' . $e, array(), WATCHDOG_ERROR);
    drupal_set_message('Node save error: ' . $e, "error");
    return FALSE;
  }
}


/**
 * Send request to connect2data.com
 *
 * This function under development
 */
function reiscout_connect2data_api_send_request($params = NULL) {

  $request = reiscout_connect2data_api_build_request($params);

  $defaults = array(
      CURLOPT_URL             => API_URL,
      CURLOPT_POST            => TRUE,
      CURLOPT_FRESH_CONNECT   => TRUE,
      CURLOPT_POSTFIELDS      => $request,
      CURLOPT_RETURNTRANSFER  => TRUE,
      CURLOPT_SSL_VERIFYPEER  => FALSE,
      CURLOPT_SSL_VERIFYHOST  => FALSE,
      CURLOPT_HTTPHEADER      => array(
          'Accept' => 'application/x-www-form-urlencoded; charset=utf-8',
      ),
  );

  $ch = curl_init();
  curl_setopt_array($ch, $defaults);

  // Send request to connect2data.com via curl()
  if (!$response = curl_exec($ch)) {
    watchdog('reiscout_connect2data_api', 'Network error: ' . curl_error($ch), array(), WATCHDOG_ERROR);
    drupal_set_message("Network error: " . curl_error($ch), "error");
    return FALSE;
  }
  curl_close($ch);

  return $response;
}


/**
 * Build request to connect2data.com
 * This function is still under development and not in use.
 * We should use some xml builder here.
 */
function reiscout_connect2data_api_build_request($params = NULL) {
  // Custom (testing) XML for request
  return '<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE REQUEST_GROUP SYSTEM "C2DRequestv2.0.dtd">
<REQUEST_GROUP MISMOVersionID="2.1">
<REQUEST _ServicePassword="enter_value" _ServiceUsername="enter_value" _JobIdentifier="enter_value" LoginAccountPassword="enter_value" LoginAccountIdentifier="C2TU000003">
<KEY _Value="12345" _Name="CEID"/>
<KEY _Value="SaveDisclosureTest20151202U" _Name="LoanNumber"/>
<KEY _Value="Tester" _Name="LenderName"/>
<KEY _Value="1.0.0" _Name="ReportVersion"/>
<KEY _Value="MortgageLoan" _Name="LoanType"/>
<REQUESTDATA><PROPERTY_INFORMATION_REQUEST _ActionType="GetAuditReport">
<_CONNECT2DATA_PRODUCT _ComplianceEase="Y" _IncludePDFIndicator="Y"/>
            <EMBEDDED_FILE>
     <DOCUMENT>
<!—Embedded CE ComplianceAnalyzer payload -->
     </DOCUMENT>
            </EMBEDDED_FILE>
</PROPERTY_INFORMATION_REQUEST>
</REQUESTDATA>
</REQUEST>
</REQUEST_GROUP>';
}


/**
 * Extends SimpleXMLElement to get attributes
 * ToDo: move class to separate file and declare it in info file for autoloading
 */
class simple_xml_extended extends SimpleXMLElement {
  public function Attribute($name)
  {
    foreach($this->Attributes() as $key=>$val)
    {
      if($key == $name)
        return (string)$val;
    }
  }
}


/**
 * Fill up array of address values for debugging
 * ToDo: move func to separate file and add modulename prefix.
 */
function fillup_debug_adresses() {
  return array(
    129 => array(
      'first_name'  => 'John',
      'last_name'   => 'Jackson',
      'address'     => '209 S Point Blvd',
      'city'        => 'McDonough',
      'state'       => 'GA',
      'zip'         => 30252,
      'country'     => 'US'
    ),
    143 => array(
      'first_name'  => 'Adam',
      'last_name'   => 'Savage',
      'address'     => '534 Grant Street Southwest',
      'city'        => 'Atlanta',
      'state'       => 'GA',
      'zip'         => 30315,
      'country'     => 'US'
    ),
    144 => array(
      'first_name'  => 'Serge',
      'last_name'   => 'Marchall',
      'address'     => '585-589 Parsons St SW',
      'city'        => 'Atlanta',
      'state'       => 'GA',
      'zip'         => 30314,
      'country'     => 'US'
    ),
    147 => array(
      'first_name'  => 'Jack',
      'last_name'   => 'Johnson',
      'address'     => '526 Beckwith St SW',
      'city'        => 'Atlanta',
      'state'       => 'GA',
      'zip'         => 30314,
      'country'     => 'US'
    ),
    153 => array(
      'first_name'  => 'Karry',
      'last_name'   => 'Brown',
      'address'     => '274 Northwind Dr',
      'city'        => 'Stockbridge',
      'state'       => 'GA',
      'zip'         => 30281,
      'country'     => 'US'
    ),
    154 => array(
      'first_name'  => 'Jim',
      'last_name'   => 'Carrey',
      'address'     => '113 Bay Court Drive',
      'city'        => 'Stockbridge',
      'state'       => 'GA',
      'zip'         => 30281,
      'country'     => 'US'
    ),
    155 => array(
      'first_name'  => 'James',
      'last_name'   => 'Blunt',
      'address'     => '637 Parsons Street Southwest',
      'city'        => 'Stockbridge',
      'state'       => 'GA',
      'zip'         => 30281,
      'country'     => 'US'
    ),
    156 => array(
      'first_name'  => 'Barry',
      'last_name'   => 'White',
      'address'     => '426 Cairo Street Northwest',
      'city'        => 'Atlanta',
      'state'       => 'GA',
      'zip'         => 30314,
      'country'     => 'US'
    ),
    157 => array(
      'first_name'  => 'James',
      'last_name'   => 'Arthur',
      'address'     => '102 Ivy Manor',
      'city'        => 'Stockbridge',
      'state'       => 'GA',
      'zip'         => 30281,
      'country'     => 'US'
    ),
    158 => array(
      'first_name'  => 'Andrew',
      'last_name'   => 'Huang',
      'address'     => '545 Grant St SW',
      'city'        => 'Atlanta',
      'state'       => 'GA',
      'zip'         => 30315,
      'country'     => 'US'
    ),
  );
}
