<?php
/**
 * @file
 * Drupal needs this blank file.
 */

function reiscout_address_init() {
  $modulePath = drupal_get_path('module', 'reiscout_address');
  drupal_add_css($modulePath . '/reiscout_address.css');
}

/**
 * Implements hook_services_resources().
 */
function reiscout_address_services_resources() {
  $file = array(
    'type'   => 'inc',
    'module' => 'reiscout_address',
    'name'   => 'reiscout_address.resource'
  );

  $resource = array(
    'addressapi' => array(
      'actions' => array(
        'setview' => array(
          'help' => t('Save view address click statistics.'),
          'callback' => 'reiscout_address_resource_action_view_address',
          'access callback' => 'reiscout_address_resource_access',
          'file' => $file,
          'args' => array(
            array(
              'name' => 'nid',
              'optional' => FALSE,
              'source' => array('data' => 'nid'),
              'type' => 'int',
            ),
          ),
        )
      ),
    ),
  );

  return $resource;
}

/**
 * Access callback for addressapi:setview action.
 */
function reiscout_address_resource_access($nid) {
  $node = node_load($nid);

  return ($node && $node->type === 'property' && !user_is_anonymous() && $node->uid !== $GLOBALS['user']->uid);
}

/**
 * Implements hook_rest_server_request_parsed_alter().
 */
function reiscout_address_rest_server_request_parsed_alter(&$data, $controller) {
  // If services was requested to create a Property node
  if ('_node_resource_create' == $controller['callback'] && 'property' == $data['type']) {
    _reiscout_address_prepare_data_to_address_autocomplete_widget($data);
  }
  // If services was requested to update a Property node
  elseif ('_node_resource_update' == $controller['callback'] && 'property' == $data['node']['type']) {
    _reiscout_address_prepare_data_to_address_autocomplete_widget($data['node']);
  }
}

/**
 * Prepares field data for 'Addressfield Autocomplete' widget.
 *
 * Data for the field_address field that comes from the mobile application is
 * compatible with standard 'Dynamic address form' widget which provided by
 * Address Field module. But we use 'Addressfield Autocomplete' widget which
 * provided by Addressfield Autocomplete module. So we need to prepare data
 * to the last widget before send it for saving.
 */
function _reiscout_address_prepare_data_to_address_autocomplete_widget(&$node) {
  $node['field_address']['und'][0]['latitude'] = $node['field-address-und-0-value-latitude'];
  $node['field_address']['und'][0]['longitude'] = $node['field-address-und-0-value-longitude'];
  $node['field_address']['und'][0] = array(
    'field_address' => array(
      'reveal' => 0,
      'autocomplete' => $node['field-address-und-0-value-autocomplete'],
      'widget' => $node['field_address']['und'][0],
    ),
  );

  // We don't need these auxiliary fields anymore.
  unset($node['field-address-und-0-value-autocomplete']);
  unset($node['field_address_autocomplete_markup']);
  unset($node['field-address-und-0-value-latitude']);
  unset($node['field-address-und-0-value-longitude']);
}

/**
 * Implements hook_entity_load().
 */
function reiscout_address_entity_load($entities, $type) {
  if ($type === 'node' && !user_is_anonymous()) {
    foreach ($entities as $entity) {
      if ($entity->type === 'property') {
        // Set $entity->_flag_is_user_has_view to TRUE for property node is user its author or has flagged the node.
        //  it is used by mobile App, see reiscout_address.js app module.
        //$entity->_flag_is_user_has_view = ($entity->uid === $GLOBALS['user']->uid || reiscout_address_user_has_view($entity->nid));
        // @todo: replace it to _purchased_property_info

        // this is a tmp placeholder to do not brake mApp part.
        $entity->_flag_is_user_has_view = true;

        // We will use this data in mobile app to fill some of the fields that related to field_address field.
        if (isset($entity->field_address[LANGUAGE_NONE][0])) {
          $data = unserialize($entity->field_address[LANGUAGE_NONE][0]['data']);
          // Prepare data
          unset($data['zoom']);
          $entity->field_address[LANGUAGE_NONE][0]['data_json'] = json_encode($data);
        }
      }
    }
  }
}

/*
 * this is a dummy func to escape erros on mApp.
 * remove it when it is not needed anymore
 */
function reiscout_address_user_has_view ($arg) {

}

/*
 * this is a dummy func to escape erros on mApp.
 * remove it when it is not needed anymore
 */
function reiscout_address_set_view ($arg) {
  
}
