<?php
/**
 * @file
 * Code for the Reiscout Address feature.
 */

include_once 'reiscout_address.features.inc';

define('REISCOUT_ADDRESS_VIEWED_FLAG', 'reiscout_address_viewed_by_user');

/**
 * Implements hook_services_resources().
 */
function reiscout_address_services_resources() {
  $file = array(
    'type'   => 'inc',
    'module' => 'reiscout_address',
    'name'   => 'reiscout_address.resource'
  );

  $resource = array(
    'addressapi' => array(
      'actions' => array(
        'setview' => array(
          'help' => t('Save view address click statistics.'),
          'callback' => 'reiscout_address_resource_action_view_address',
          'access callback' => 'reiscout_address_resource_access',
          'file' => $file,
          'args' => array(
            array(
              'name' => 'nid',
              'optional' => FALSE,
              'source' => array('data' => 'nid'),
              'type' => 'int',
            ),
          ),
        )
      ),
    ),
  );

  return $resource;
}

/**
 * Access callback for addressapi:setview action.
 */
function reiscout_address_resource_access($nid) {
  $node = node_load($nid);

  return ($node && $node->type === 'property' && !user_is_anonymous() && $node->uid !== $GLOBALS['user']->uid);
}

/**
 * Implements hook_entity_load().
 */
function reiscout_address_entity_load($entities, $type) {
  if ($type === 'node' && !user_is_anonymous()) {
    foreach ($entities as $entity) {
      if ($entity->type === 'property') {
        // Set $entity->_flag_is_user_has_view to TRUE for property node is user its author or has flagged the node.
        //  it is used by mobile App, see reiscout_address.js app module.
        $entity->_flag_is_user_has_view = ($entity->uid === $GLOBALS['user']->uid || reiscout_address_user_has_view($entity->nid));
      }
    }
  }
}

/**
 * Implements hook_menu
 *
 * ajax callback to show the modal or place address
 */
function reiscout_address_menu () {
  $items['reiscout_address_ajax_callback/%ctools_js/%node'] = array(
    'page callback' => 'reiscout_address_button_ajax_callback',
    'page arguments' => array(1, 2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements menu callback for ajax request to reiscout_address_ajax_callback/%ctools_js/%node path..
 */
function reiscout_address_button_ajax_callback($js = NULL, $node) {
  if (user_is_anonymous()) {
    // For anonymous show login modal.
    ctools_include('modal');
    ctools_include('ajax');
    $form_state = array(
      'title' => t('Login'),
      'ajax' => TRUE,
    );
    $output = ctools_modal_form_wrapper('user_login', $form_state);
    if (!empty($form_state['executed'])) {
      $commands[] = ctools_ajax_command_redirect('node/'.$node->nid, $delay = 0, $options = array());
      print ajax_render($commands);
      exit;
    }
    print ajax_render($output);
    exit;
  } else {
    // For logged in replace 'show address' button with the address itself.
    $address = reiscout_address_get_address($node);
    reiscout_address_set_view($node->nid);
    $commands[] = ajax_command_html('#address-ajax-placeholder', $address);
    print ajax_render($commands); // this function exits.
    exit;
  }
}

/**
 * Implements hook_node_view
 * For not authorized user show a button showing the modal
 * For authorized user who have no the flag show a button instead of address
 * For authorized user who have the flag show the address
 * Hide for others
 */
function reiscout_address_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full' && $node->type == 'property') {
    // For authorized user who have the flag (already viewed the address) show the address
    if (!user_is_anonymous() && ($node->uid === $GLOBALS['user']->uid || reiscout_address_user_has_view($node->nid))) {
      return;
    }

    // Replace the address with the button for all others.
    ctools_include('ajax');
    // We may need a modal, so add modal required JS
    ctools_include('modal');
    ctools_modal_add_js();

    $button = ctools_ajax_text_button(t('Show Address'), "reiscout_address_ajax_callback/nojs/".$node->nid, t('alt text'), 'address-placeholder');
    $button = '<span id="address-ajax-placeholder">'.$button.'</span>';
    $node->content['field_address_text'][0]['#markup'] = $button;
  }
}

/**
 * Set the flag that node has been viewed by the user
 */
function reiscout_address_set_view($nid, $account = NULL) {
  return flag('flag', REISCOUT_ADDRESS_VIEWED_FLAG, $nid, $account);
}

/**
 * Set the flag that node has been viewed by the user
 */
function reiscout_address_user_has_view($nid, $uid = null) {
  $flags = flag_get_user_flags('node', $nid, $uid);
  if (array_key_exists(REISCOUT_ADDRESS_VIEWED_FLAG, $flags)) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Set the flag that node has been viewed by the user
 */
function reiscout_address_get_address($node) {
  return $node->field_address_text[LANGUAGE_NONE][0]['value'];
}

/**
 * Implements hook_form_alter().
 */
function reiscout_address_form_property_node_form_alter(&$form, &$form_state, $form_id) {
  static $fieldName = 'field_address_text';

  if (isset($form[$fieldName])) {
    $language = (empty($form[$fieldName]['#language']) ? LANGUAGE_NONE : $form[$fieldName]['#language']);
    $autocomplete = [];
    
    if (isset($form[$fieldName][$language])) {
      foreach ($form[$fieldName][$language] as $delta => &$field) {
        if (!isset($field['value'])) {
          continue;
        }

        $element = &$field['value'];

        if (!isset($element['#field_suffix'])) {
          $element['#field_suffix'] = '';
        }

        $idPrefix = 'clear-address-button';
        $idSuffix = drupal_html_id(implode('-', [$fieldName, $language, $delta, 'value']));
        $link = l('Clear Address', current_path(), [
          'fragment' => $idPrefix . '-' . $idSuffix,
          'attributes' => [
            'id' => $idPrefix . '-' . $idSuffix,
            'class' => [$idPrefix],
            'data-input-id' => 'edit-' . $idSuffix,
          ],
        ]);
        
        $autocomplete[] = 'edit-' . $idSuffix;
        $element['#field_suffix'] = $link . $element['#field_suffix'];

        unset($element, $field);
      }
    }

    $modulePath = drupal_get_path('module', 'reiscout_address');

    drupal_add_css($modulePath . '/reiscout_address.css');
    drupal_add_js(array('reiscout_address_autocomplete' => $autocomplete), 'setting');
    drupal_add_js('https://maps.googleapis.com/maps/api/js?libraries=places');
    drupal_add_js($modulePath . '/geocomplete/jquery.geocomplete.min.js');
    drupal_add_js($modulePath . '/reiscout_address.js');
  }
}
