<?php

/**
 * @file
 * Install, update and uninstall functions for the Reiscout Equity Percentage module.
 */

/**
 * Implements hook_uninstall().
 */
function reiscout_equity_percentage_uninstall() {
  // Remove any items from the reiscout_equity_percentage_recalculate queue if still there.
  DrupalQueue::get('reiscout_equity_percentage_recalculate')->deleteQueue();

  variable_del('reiscout_equity_percentage_last_calculated');
}
