<?php

/**
 * @file
 * Customize commerce modules behaviours for reiscout project needs.
 *
 * Implements address access control.
 *
 * Implementation path:
 * For each property create an individual product referencing the property
 *   Property  can be referenced only once by each product type
 *
 * On product add to cart calculate its price and set to line item
 *   https://drupalcommerce.org/discussions/2475/how-dynamically-calculate-sell-price-product-using-rules
 * A rule to Limit each product quantity to 1 and shows the message that product already in cart
 * Admin UI to set prices for new products and update for existed
 * API that get all purchased nids by user of given product type
 *   http://stackoverflow.com/questions/8148138/getting-all-products-owned-by-a-user
 * Access hook that show address only if it is purchased
 * Cart form alter that shows the right product type and only if it is not purchased already
 */

define('REISCOUT_PROPERTY_COMMERCE_ADDRESS_ACCESS_PRODUCT_TYPE', 'reiscout_property_address_access');
define('REISCOUT_PROPERTY_COMMERCE_OWNER_INFO_PRODUCT_TYPE', 'reiscout_property_owner_info');
define('REISCOUT_PROPERTY_COMMERCE_NODE_TYPE', 'property');

require_once 'reiscout_property_commerce.inc';

function reiscout_property_commerce_menu () {
  // Module settings.
  $items['admin/commerce/config/reiscout'] = array(
    'title' => 'Reiscout Commerce Settings',
    'description' => 'Reiscout settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('reiscout_property_commerce_settings_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'reiscout_property_commerce.admin.inc',
  );

  return $items;
}

/**
 * List of fields to sell access to
 */
function reiscout_property_commerce_fields_access_to_sell() {
  return array(
    'field_address_text',
  );
}

/**
 * Implements hook_field_access.
 */
function reiscout_property_commerce_field_access($op, $field, $entity_type, $entity, $account) {

  // Show property address fields only for
  // - admin role
  // - property owner
  // - user purchased the address

  // Do nothing if current user is admin
  if ($account->uid == 1) {
    return;
  }

  // Access control for field_address in picture node.
  if ($op == 'view' && $entity_type == 'node' && !empty($entity->type) && $entity->type == REISCOUT_PROPERTY_COMMERCE_NODE_TYPE
  &&  in_array($field['field_name'], reiscout_property_commerce_fields_access_to_sell() ) ) {

    // Allow access if user is an author.
    if ($entity->uid == $account->uid) {
      return TRUE;
    }

    // Allow access if user purchased the node.
    if (reiscout_property_commerce_is_node_purchased($entity->nid, REISCOUT_PROPERTY_COMMERCE_ADDRESS_ACCESS_PRODUCT_TYPE, $account->uid)) {
      return TRUE;
    }

    // Deny access otherwise
    return FALSE;
  }
}

/**
 * Implements hook_form_alter().
 */
function reiscout_property_commerce_form_property_node_form_alter(&$form, &$form_state, $form_id) {
  // Hide product selection on property node edit page.
  $form['field_product']['#access'] = FALSE;
}

/**
 * Implements hook_node_view_alter().
 */
function reiscout_property_commerce_node_view_alter(&$build) {
  if (isset($build['#node']) && $build['#node']->type === 'property' && isset($build['#view_mode']) && $build['#view_mode'] === 'full') {
    module_load_include('inc', 'popup', 'includes/popup.api');

    $popupOptions = array(
      'block' => true,
      'module' => 'mailchimp_signup',
      'delta' => 'we_arent_ready_yet',
      'activate' => 'click',
      'ajax' => true,
      'close' => true,
      'width' => 400,
      'class' => 'we-arent-ready-yet-popup',
    );

    $fields = array(
      'field_address_access_product' => array(
          'title' => 'Buy Property Address for @price @cur',
          'price callback' => 'reiscout_property_commerce_get_property_address_price',
          'price callback args' => array($build['#node']),
      ),
      'field_owner_info_product' => array(
          'title' => 'Buy Owner Info for @price @cur',
          'price callback' => 'reiscout_property_commerce_get_owner_info_price',
      )
    );

    foreach ($fields as $field => $options) {
      if (isset($build[$field])) {
        $price = call_user_func_array($options['price callback'], (isset($options['price callback args']) ? $options['price callback args'] : array()));
        $build[$field] = array(
            '#markup' => popup(array_merge($popupOptions, array(
              'title' => t($options['title'], array(
                '@price' => commerce_currency_amount_to_decimal($price['amount'], $price['currency_code']),
                '@cur' => $price['currency_code'],
              ))
            ))),
            '#prefix' => '<div>',
            '#suffix' => '</div>',
            '#weight' => $build[$field]['#weight'],
        );
      }
    }
  }
}

/**
 * Implements hook_node_presave().
 */
function reiscout_property_commerce_node_presave($node) {
  return;
  // Assign products to property nodes on save.
  if (!($node->type == REISCOUT_PROPERTY_COMMERCE_NODE_TYPE)) {
    return;
  }

  // Looking for existed product or create one and attach to node if it is not attached yet
  if (empty($node->field_owner_info_product[LANGUAGE_NONE][0])) {
    $owner_info_product = reiscout_property_commerce_load_product_by_property(REISCOUT_PROPERTY_COMMERCE_OWNER_INFO_PRODUCT_TYPE, $node->nid);
    if (!$owner_info_product) {
      $owner_info_product = reiscout_property_commerce_create_product(REISCOUT_PROPERTY_COMMERCE_OWNER_INFO_PRODUCT_TYPE, $node);
    }

    $node->field_owner_info_product[LANGUAGE_NONE][0]['product_id'] = $owner_info_product->product_id;
  }
  // Update price for existed attached product
  $owner_info_product = (!isset($owner_info_product)) ? commerce_product_load($node->field_owner_info_product[LANGUAGE_NONE][0]['product_id'])
    : $owner_info_product;

  // Its call is cheap as $node already in cache and wouldnt be loaded again and if prices are the theme product would not be saved.
  reiscout_property_commerce_update_price($owner_info_product);

  // The save as for above for address access product
  // Looking for existed product or create one and attach to node if it is not attached yet
  if (empty($node->field_address_access_product[LANGUAGE_NONE][0])) {
    $address_access_product = reiscout_property_commerce_load_product_by_property(REISCOUT_PROPERTY_COMMERCE_ADDRESS_ACCESS_PRODUCT_TYPE, $node->nid);
    if (!$address_access_product) {
      $address_access_product = reiscout_property_commerce_create_product(REISCOUT_PROPERTY_COMMERCE_ADDRESS_ACCESS_PRODUCT_TYPE, $node);
    }
    $node->field_address_access_product[LANGUAGE_NONE][0]['product_id'] = $address_access_product->product_id;
  }
  // Update price for existed attached product
  $address_access_product = (!isset($address_access_product)) ? commerce_product_load($node->field_address_access_product[LANGUAGE_NONE][0]['product_id'])
    : $address_access_product;

  // Its call is cheap as $node already in cache and wouldnt be loaded again and if prices are the theme product would not be saved.
  reiscout_property_commerce_update_price($address_access_product);
}

/**
 * Implements hook_form_alter().
 */
function reiscout_property_commerce_form_alter(&$form, &$form_state, $form_id) {
  if (substr_count($form_id, 'commerce_cart_add_to_cart_form_') == 1) {
    reiscout_property_commerce_form_commerce_cart_form_alter($form, $form_state, $form_id);
  }
}

/**
 * It is NOT a hook and called from reiscout_property_commerce_form_alter
 */
function reiscout_property_commerce_form_commerce_cart_form_alter(&$form, &$form_state, $form_id) {
  // Check that product type is the one needed to be processed.
  $product = commerce_product_load($form['product_id']['#value']);
  if (!in_array($product->type, array(
    REISCOUT_PROPERTY_COMMERCE_ADDRESS_ACCESS_PRODUCT_TYPE,
    REISCOUT_PROPERTY_COMMERCE_OWNER_INFO_PRODUCT_TYPE
  ))) {
    return;
  }

  $node = node_load($form_state['context']['entity_id']);
  
  if ($product->type == REISCOUT_PROPERTY_COMMERCE_OWNER_INFO_PRODUCT_TYPE) {
    // Check to allow user to buy owner info
    if ($node->uid == $GLOBALS['user']->uid
      && !reiscout_property_commerce_is_node_purchased($node->nid, REISCOUT_PROPERTY_COMMERCE_OWNER_INFO_PRODUCT_TYPE, $GLOBALS['user']->uid)) {
      $price = reiscout_property_commerce_get_owner_info_price();
      $form['submit']['#value'] = t('Buy Owner Info for @price @cur',
        array(
          '@price' => commerce_currency_amount_to_decimal($price['amount'], $price['currency_code']),
          '@cur' => $price['currency_code'],
        )
      );
    } elseif(!user_access('administer site configuration')) {
      $form['#access'] = FALSE;
    }
  }

  if ($product->type == REISCOUT_PROPERTY_COMMERCE_ADDRESS_ACCESS_PRODUCT_TYPE) {
    // Check to allow user to buy an address
    if ($node->uid != $GLOBALS['user']->uid
      && !reiscout_property_commerce_is_node_purchased($node->nid, REISCOUT_PROPERTY_COMMERCE_ADDRESS_ACCESS_PRODUCT_TYPE, $GLOBALS['user']->uid)) {
      $price = reiscout_property_commerce_get_property_address_price($node);
      $form['submit']['#value'] = t('Buy Property Address for @price @cur',
        array(
          '@price' => commerce_currency_amount_to_decimal($price['amount'], $price['currency_code']),
          '@cur' => $price['currency_code'],
        )
      );
    } elseif(!user_access('administer site configuration')) {
      $form['#access'] = FALSE;
    }
  }
}

function reiscout_property_commerce_init() {

}
