<?php
/**
 * @file
 * Code for the Reiscout Data Quality Tags feature.
 */

include_once 'reiscout_data_quality_tags.features.inc';

/**
 * Implements hook_node_presave().
 */
function reiscout_data_quality_tags_node_presave($node) {
  if ('property' != $node->type) {
    return;
  }

  $nw = entity_metadata_wrapper('node', $node);

  $is_owner_address_filled = _reiscout_property_is_owner_address_filled_by_nid($node);
  $is_data_verified = FALSE;

  // Check if the author of a node has an 'administrator' role
  $node_author = user_load($nw->author->uid->value());
  $role_admin = user_role_load_by_name('administrator');
  if (user_has_role($role_admin->rid, $node_author)) {
    $is_data_verified = TRUE;
  }

  // Check if the 'Locked data' field of a node is set to true
  if ($nw->field_data_locked->value()) {
    $is_data_verified = TRUE;
  }

  if ($is_owner_address_filled) {
    // Add the 'Owner info' tag
    _reiscout_data_quality_tags_add($nw->field_data_quality_tags, 'owner_info');
  }
  else {
    // Remove the 'Owner info' tag
    _reiscout_data_quality_tags_remove($nw->field_data_quality_tags, 'owner_info');
  }

  if ($is_data_verified) {
    // Add the 'Verified data' tag
    _reiscout_data_quality_tags_add($nw->field_data_quality_tags, 'verified_data');
  }
  else {
    // Remove the 'Verified data' tag
    _reiscout_data_quality_tags_remove($nw->field_data_quality_tags, 'verified_data');
  }
}

/**
 * Adds a tag into a multiple-value 'field_data_quality_tags' field
 */
function _reiscout_data_quality_tags_add($field, $tag_name) {
  $tag = taxonomy_term_machine_name_load($tag_name, 'data_quality_tags');
  if (!in_array($tag, $field->value())) {
    $field[] = $tag;
  }
}

/**
 * Removes a tag from a multiple-value 'field_data_quality_tags' field
 */
function _reiscout_data_quality_tags_remove($field, $tag_name) {
  $tag = taxonomy_term_machine_name_load($tag_name, 'data_quality_tags');
  foreach ($field as $tw) {
    if ($tag == $tw->value()) {
      $tw->set(NULl);
      break;
    }
  }
}
